# Generated by Django 4.2.11 on 2026-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='body',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
