# Generated by Django 4.2.11 on 2026-02-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_add_to_footer_staticpage_show_in_footer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='external_link',
        ),
    ]
