# Generated by Django 4.2.11 on 2026-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_staticpage_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='footer_order',
            field=models.IntegerField(blank=True, default=0, help_text='Controls the order of this page in the footer (lower comes first).', null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='If enabled, this page will appear in the site footer.'),
        ),
    ]
