# Generated by Django 4.2.11 on 2025-12-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsubmission_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
