# Generated by Django 4.2.11 on 2025-12-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_normalize_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(blank=True, choices=[('culture', 'Culture'), ('craft', 'Craft'), ('sustainability', 'Sustainability'), ('news', 'News')], max_length=50),
        ),
    ]
