# Generated by Django 4.2.11 on 2026-01-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='home/sections/')),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
