# Generated by Django 4.2.11 on 2026-01-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='embed_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='embed_url',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='home/videos/'),
        ),
    ]
