# Generated by Django 4.2.11 on 2026-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='embed_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
