# Generated by Django 4.2.11 on 2026-01-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagevideo_embed_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homepage/videos/'),
        ),
    ]
