# Generated by Django 4.2.11 on 2026-01-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagevideo_embed_url_alter_homepagevideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontentsection',
            name='header',
            field=models.CharField(blank=True, help_text='Section header shown above the content block on the Home page', max_length=200),
        ),
    ]
