# Generated by Django 4.2.11 on 2026-01-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homecontentsection_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_label', models.CharField(blank=True, help_text='Small red label shown above the title (e.g. THE OCHRE WORLD)', max_length=120)),
                ('title', models.CharField(blank=True, help_text='Main section title (Playfair Display)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Section description (Satoshi)')),
            ],
            options={
                'verbose_name': 'Home Page - Content Section Header',
                'verbose_name_plural': 'Home Page - Content Section Header',
            },
        ),
    ]
