# Generated by Django 4.2.11 on 2026-01-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
