# Generated by Django 4.2.11 on 2025-12-11 11:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='full_description',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopitem', to='shop.shopcategory'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
