# Generated by Django 4.2.11 on 2025-12-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_cart_cartitem_order_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(limit_choices_to={'is_experience': True}, on_delete=django.db.models.deletion.CASCADE, related_name='experience_bookings', to='shop.shopitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience Booking',
                'verbose_name_plural': 'Experience Bookings',
                'ordering': ('-created_at',),
            },
        ),
    ]
