# Generated by Django 4.2.11 on 2026-01-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_options_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='caption',
            field=models.CharField(blank=True, help_text='Short caption shown in shop listings', max_length=255),
        ),
    ]
