# Generated by Django 4.2.11 on 2026-01-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_options_order_currency_and_more'),
        ('shop', '0004_alter_time_slot_to_timefield'),
    ]

    operations = [
    ]
