# Generated by Django 4.2.11 on 2026-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopitem_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='allowed_pincodes',
            field=models.TextField(blank=True, help_text='Comma-separated pincodes where this product is available. Leave empty for all locations.'),
        ),
    ]
