# Generated by Django 4.2.11 on 2026-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopitem_allowed_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
