# Generated by Django 4.2.11 on 2025-12-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_producttype_productunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={},
        ),
        migrations.RenameField(
            model_name='productunit',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='productunit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shop.shopitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='value',
            field=models.CharField(default='unit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.unittype'),
        ),
    ]
