# Generated by Django 4.2.11 on 2025-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='category',
            field=models.CharField(choices=[('gin', 'Gin'), ('vodka', 'Vodka'), ('limited_edition', 'Limited Edition'), ('special_release', 'Special Release')], default='gin', max_length=50),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
