# Generated by Django 4.2.11 on 2026-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0004_populate_categories_and_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['display_order', '-id']},
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
