# Generated by Django 4.2.11 on 2025-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_logo', models.ImageField(blank=True, null=True, upload_to='media/logos/')),
                ('date', models.DateField()),
                ('excerpt', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
