# Generated by Django 4.2.11 on 2025-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='press_kits/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pressarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pressarticle',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='pressarticle',
            name='publication_logo',
        ),
        migrations.RemoveField(
            model_name='pressarticle',
            name='url',
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='press/'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
